import React, { createContext, useContext, useState, useMemo, useCallback } from 'react';

type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
  formatPrice: (price: number) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const esMessages = {
  "nav_woman": "Mujer",
  "nav_man": "Hombre",
  "nav_discounts": "Descuentos",
  "brand_subtitle": "Bolsos & Moda",
  "search_placeholder": "Buscar productos...",
  "search_aria_label": "Abrir búsqueda",
  "close_search_aria_label": "Cerrar búsqueda",
  "category_bags": "Bolsos",
  "category_clothing": "Ropa",
  "category_accessories": "Accesorios",
  "view_all": "Ver todo",
  "cart_aria_label": "Ver carrito con {count} artículos",
  "footer_social": "Redes Sociales",
  "footer_about": "Acerca de Chic 44",
  "footer_info": "Información",
  "footer_contact": "Contacto",
  "footer_company": "La empresa",
  "footer_work_with_us": "Trabaje con nosotros",
  "footer_our_stores": "Nuestras tiendas",
  "footer_terms": "Términos y condiciones",
  "footer_warranties": "Garantías y devoluciones",
  "footer_customer_service": "Servicio al cliente y PQRS",
  "footer_data_policy": "Tratamiento de datos personales",
  "home_featured_products": "Productos Destacados",
  "product_back_to_products": "Volver a productos",
  "product_reference": "Referencia",
  "product_color": "Color",
  "product_size_bags": "Tamaño",
  "product_size_clothes": "Talla",
  "product_add_to_cart": "Añadir al carrito",
  "product_buy_now": "Comprar",
  "product_added_alert": "{quantity} x {name} ({color}, {size}) añadido al carrito!",
  "cart_title": "Tu Carrito de Compras",
  "cart_empty_title": "Tu carrito está vacío",
  "cart_empty_text": "Parece que no has añadido nada a tu carrito todavía.",
  "cart_continue_shopping": "Seguir comprando",
  "cart_item_color": "Color",
  "cart_item_size_bags": "Tamaño",
  "cart_item_size_clothes": "Talla",
  "cart_remove_item_aria": "Eliminar {name}",
  "cart_summary_title": "Resumen del Pedido",
  "cart_summary_subtotal": "Subtotal",
  "cart_summary_shipping": "Envío",
  "cart_summary_shipping_cost": "Gratis",
  "cart_summary_total": "Total",
  "cart_summary_checkout": "Proceder al Pago",
  "cart_summary_clear": "Vaciar Carrito",
  "checkout_back_to_cart": "Volver al carrito",
  "checkout_title": "Métodos de pago",
  "checkout_pay_with_qr": "Pagar con QR",
  "checkout_qr_instructions": "Escanea el siguiente código QR con tu aplicación de pagos para completar la compra.",
  "checkout_terms_agreement": "Al continuar, aceptas nuestros {link}.",
  "checkout_terms_link": "Términos y Condiciones",
  "footer_copyright": "© {year} Chic 44. Todos los derechos reservados. El contenido de este sitio web no puede ser reproducido sin el consentimiento expreso del titular.",
  "slide_1_title": "CHIC 44",
  "slide_1_subtitle": "Bolsos & Moda",
  "slide_2_title": "NUEVA COLECCIÓN",
  "slide_2_subtitle": "Descubre las últimas tendencias",
  "slide_3_title": "ENVÍOS GRATIS",
  "slide_3_subtitle": "En pedidos superiores a $200.000 COP",
  "footer_subscribe_title": "Suscríbete",
  "footer_subscribe_text": "Recibe nuestras últimas noticias y ofertas especiales directamente en tu bandeja de entrada.",
  "footer_subscribe_placeholder": "Tu correo electrónico",
  "footer_subscribe_button": "Unirse",
  "footer_subscribe_thanks": "¡Gracias por suscribirte!",
  "footer_subscribe_privacy": "Respetamos tu privacidad. Puedes cancelar tu suscripción en cualquier momento.",
  "profile_title": "Mi Perfil",
  "profile_orders": "Mis Pedidos",
  "profile_orders_text": "Aún no tienes pedidos. ¡Cuando hagas uno, aparecerá aquí!",
  "profile_details": "Mis Datos",
  "profile_name": "Nombre",
  "profile_email": "Correo Electrónico",
  "profile_logout": "Cerrar Sesión",
  "profile_mobile_link": "Mi Perfil",
  "no_products_in_category": "No hay productos en esta categoría.",
  "product_s27office_name": "Morral Studio27 fashion standard grande",
  "product_s27office_desc": "Cuero Ecológico",
  "product_okroffice_name": "Bolso grande cuadriculado",
  "product_okroffice_desc": "Cuero Ecológico",
  "product_elegantoffice_name": "Bolso studio 27 acartonado grande beige",
  "product_elegantoffice_desc": "Cuero Ecológico Importado",
  "product_standaroffice_name": "Bolso studio 27 acartonado grande cafe",
  "product_standaroffice_desc": "Cuero Ecológico",
  "product_cuerooffice_name": "CueroOffice",
  "product_cuerooffice_desc": "Cuero Genuino",
  "product_vestido_floral_name": "Blusa blanca estampada con flores",
  "product_vestido_floral_desc": "Blusa ligera con un vibrante estampado floral, perfecta para cualquier ocasión casual.",
  "product_blusa_elegante_name": "Blusa Elegante de Seda",
  "product_blusa_elegante_desc": "Blusa de seda suave con un corte moderno y elegante, perfecta para la oficina o una salida casual.",
  "product_gafas_aviador_name": "Gafas de Sol Aviador",
  "product_gafas_aviador_desc": "Protege tus ojos con estilo. Un diseño clásico que nunca pasa de moda.",
  "product_cartera_elegant_name": "Cartera Elegant",
  "product_cartera_elegant_desc": "Un toque de elegancia para cualquier ocasión, con finos acabados.",
  "product_cartera_fiesta_name": "Cartera de Fiesta",
  "product_cartera_fiesta_desc": "El accesorio perfecto para tus eventos especiales, brilla con estilo.",
  "product_cartera_clasic_name": "Cartera Clásica",
  "product_cartera_clasic_desc": "Diseño atemporal y funcional, ideal para el día a día.",
  "subcategory_bags_office": "Oficina",
  "subcategory_bags_purses": "Cartera",
  "subcategory_bags_crossbody": "Manos Libres",
  "subcategory_bags_backpacks": "Morrales",
  "subcategory_bags_duffels": "Baúles y Maletines",
  "subcategory_bags_totes": "Tulas y Deportivos",
  "subcategory_bags_fanny": "Riñoneras",
  "subcategory_bags_lunch": "Loncheras",
  "subcategory_dresses_skirts": "Vestidos y Faldas",
  "subcategory_jackets_blazers": "Chaquetas y Blazers",
  "subcategory_wallets_cardholders": "Billeteras y Tarjeteros",
  "subcategory_belts_straps": "Cinturones y Correas",
  "subcategory_cosmetic_fanny": "Cosmetiqueras y Riñoneras",
  "subcategory_bags_baul": "Baúl",
  "subcategory_bags_morral_fashion": "Morral Fashion",
  "subcategory_bags_morral_lona": "Morral Lona",
  "subcategory_bags_maletin": "Maletín",
  "subcategory_bags_deportivo": "Deportivo",
  "subcategory_clothing_blusa": "Blusa",
  "subcategory_clothing_basica_bermuda": "Básica Bermuda",
  "subcategory_clothing_basica_camisilla": "Básica Camisilla",
  "subcategory_clothing_basica_th": "Básica TH",
  "subcategory_clothing_basica_reductora": "Básica Reductora",
  "subcategory_clothing_sueter": "Suéter",
  "subcategory_clothing_falda": "Falda",
  "subcategory_clothing_vestido_bano": "Vestido de Baño",
  "subcategory_accessories_tula": "Tula",
  "subcategory_accessories_rinonera": "Riñonera",
  "subcategory_accessories_lonchera": "Lonchera",
  "subcategory_accessories_billetera": "Billetera",
  "subcategory_accessories_monedero": "Monedero",
  "subcategory_accessories_tarjetero": "Tarjetero",
  "subcategory_accessories_gorra": "Gorra",
  "subcategory_accessories_cinturon": "Cinturón",
  "subcategory_clothing_pantalon": "Pantalón",
  "subcategory_clothing_jeans": "Jeans",
  "subcategory_clothing_vestido": "Vestido",
  "subcategory_clothing_blazer": "Blazer",
  "subcategory_clothing_deportivo": "Deportivo",
  "subcategory_clothing_camiseta": "Camiseta",
  "subcategory_clothing_pantaloneta": "Pantaloneta",
  "subcategory_clothing_jogger": "Jogger",
  "subcategory_clothing_ropa_verano": "Ropa de verano",
  "footer_company_text": "En Chic 44 vivimos la moda con pasión y autenticidad. Nos inspira ofrecer colecciones que combinan estilo, calidad y personalidad, pensadas para quienes disfrutan expresar quiénes son a través de lo que visten.",
  "footer_store_copacabana": "Copacabana",
  "footer_store_copacabana_address": "Calle 50 #48-38",
  "footer_store_girardota": "Girardota",
  "footer_store_girardota_address": "Cra 18 #6-61",
  "footer_store_barbosa": "Barbosa",
  "footer_store_barbosa_address_1": "Cra 18 #11-28",
  "footer_store_barbosa_address_2": "Pasaje Comercial Unión Parque Local 108",
  "footer_contact_email": "chic44boutique@gmail.com",
  "search_suggested_categories": "Categorías Sugeridas",
  "search_suggested_products": "Productos Sugeridos",
  "search_no_results": "No se encontraron resultados para '{query}'"
};

const enMessages = {
  "nav_woman": "Woman",
  "nav_man": "Man",
  "nav_discounts": "Discounts",
  "brand_subtitle": "Bags & Fashion",
  "search_placeholder": "Search products...",
  "search_aria_label": "Open search",
  "close_search_aria_label": "Close search",
  "category_bags": "Bags",
  "category_clothing": "Clothing",
  "category_accessories": "Accessories",
  "view_all": "View all",
  "cart_aria_label": "View cart with {count} items",
  "footer_social": "Social Media",
  "footer_about": "About Chic 44",
  "footer_info": "Information",
  "footer_contact": "Contact",
  "footer_company": "The company",
  "footer_work_with_us": "Work with us",
  "footer_our_stores": "Our stores",
  "footer_terms": "Terms and conditions",
  "footer_warranties": "Warranties and returns",
  "footer_customer_service": "Customer service and PQRS",
  "footer_data_policy": "Personal data treatment",
  "home_featured_products": "Featured Products",
  "product_back_to_products": "Back to products",
  "product_reference": "Reference",
  "product_color": "Color",
  "product_size_bags": "Size",
  "product_size_clothes": "Size",
  "product_add_to_cart": "Add to cart",
  "product_buy_now": "Buy Now",
  "product_added_alert": "{quantity} x {name} ({color}, {size}) added to cart!",
  "cart_title": "Your Shopping Cart",
  "cart_empty_title": "Your cart is empty",
  "cart_empty_text": "It seems you haven't added anything to your cart yet.",
  "cart_continue_shopping": "Continue Shopping",
  "cart_item_color": "Color",
  "cart_item_size_bags": "Size",
  "cart_item_size_clothes": "Size",
  "cart_remove_item_aria": "Remove {name}",
  "cart_summary_title": "Order Summary",
  "cart_summary_subtotal": "Subtotal",
  "cart_summary_shipping": "Shipping",
  "cart_summary_shipping_cost": "Free",
  "cart_summary_total": "Total",
  "cart_summary_checkout": "Proceed to Checkout",
  "cart_summary_clear": "Clear Cart",
  "checkout_back_to_cart": "Back to cart",
  "checkout_title": "Payment Methods",
  "checkout_pay_with_qr": "Pay with QR",
  "checkout_qr_instructions": "Scan the following QR code with your payment application to complete the purchase.",
  "checkout_terms_agreement": "By continuing, you agree to our {link}.",
  "checkout_terms_link": "Terms and Conditions",
  "footer_copyright": "© {year} Chic 44. All rights reserved. The content of this website may not be reproduced without the express consent of the owner.",
  "slide_1_title": "CHIC 44",
  "slide_1_subtitle": "Bags & Fashion",
  "slide_2_title": "NEW COLLECTION",
  "slide_2_subtitle": "Discover the latest trends",
  "slide_3_title": "FREE SHIPPING",
  "slide_3_subtitle": "On orders over $200,000 COP",
  "footer_subscribe_title": "Subscribe",
  "footer_subscribe_text": "Get our latest news and special offers directly to your inbox.",
  "footer_subscribe_placeholder": "Your email address",
  "footer_subscribe_button": "Join",
  "footer_subscribe_thanks": "Thanks for subscribing!",
  "footer_subscribe_privacy": "We respect your privacy. You can unsubscribe at any time.",
  "profile_title": "My Profile",
  "profile_orders": "My Orders",
  "profile_orders_text": "You don't have any orders yet. When you make one, it will appear here!",
  "profile_details": "My Details",
  "profile_name": "Name",
  "profile_email": "Email",
  "profile_logout": "Log Out",
  "profile_mobile_link": "My Profile",
  "no_products_in_category": "There are no products in this category.",
  "product_s27office_name": "Studio27 fashion standard large backpack",
  "product_s27office_desc": "Ecological Leather",
  "product_okroffice_name": "Large checkered bag",
  "product_okroffice_desc": "Ecological Leather",
  "product_elegantoffice_name": "Studio 27 large structured beige bag",
  "product_elegantoffice_desc": "Imported Ecological Leather",
  "product_standaroffice_name": "Studio 27 Large Structured Brown Bag",
  "product_standaroffice_desc": "Ecological Leather",
  "product_cuerooffice_name": "CueroOffice",
  "product_cuerooffice_desc": "Genuine Leather",
  "product_vestido_floral_name": "White Floral Print Blouse",
  "product_vestido_floral_desc": "Lightweight blouse with a vibrant floral print, perfect for any casual occasion.",
  "product_blusa_elegante_name": "Elegant Silk Blouse",
  "product_blusa_elegante_desc": "Soft silk blouse with a modern and elegant cut, perfect for the office or a casual outing.",
  "product_gafas_aviador_name": "Aviator Sunglasses",
  "product_gafas_aviador_desc": "Protect your eyes with style. A classic design that never goes out of fashion.",
  "product_cartera_elegant_name": "Elegant Purse",
  "product_cartera_elegant_desc": "A touch of elegance for any occasion, with fine finishes.",
  "product_cartera_fiesta_name": "Party Purse",
  "product_cartera_fiesta_desc": "The perfect accessory for your special events, shine with style.",
  "product_cartera_clasic_name": "Classic Purse",
  "product_cartera_clasic_desc": "Timeless and functional design, ideal for everyday use.",
  "subcategory_bags_office": "Office",
  "subcategory_bags_purses": "Purses",
  "subcategory_bags_crossbody": "Crossbody",
  "subcategory_bags_backpacks": "Backpacks",
  "subcategory_bags_duffels": "Duffels & Briefcases",
  "subcategory_bags_totes": "Totes & Gym Bags",
  "subcategory_bags_fanny": "Fanny Packs",
  "subcategory_bags_lunch": "Lunch Bags",
  "subcategory_dresses_skirts": "Dresses & Skirts",
  "subcategory_jackets_blazers": "Jackets & Blazers",
  "subcategory_wallets_cardholders": "Wallets & Cardholders",
  "subcategory_belts_straps": "Belts & Straps",
  "subcategory_cosmetic_fanny": "Cosmetic & Fanny Packs",
  "subcategory_bags_baul": "Duffel",
  "subcategory_bags_morral_fashion": "Fashion Backpack",
  "subcategory_bags_morral_lona": "Canvas Backpack",
  "subcategory_bags_maletin": "Briefcase",
  "subcategory_bags_deportivo": "Gym Bag",
  "subcategory_clothing_blusa": "Blouse",
  "subcategory_clothing_basica_bermuda": "Basic Bermuda",
  "subcategory_clothing_basica_camisilla": "Basic Tank Top",
  "subcategory_clothing_basica_th": "Basic TH",
  "subcategory_clothing_basica_reductora": "Basic Slimming",
  "subcategory_clothing_sueter": "Sweater",
  "subcategory_clothing_falda": "Skirt",
  "subcategory_clothing_vestido_bano": "Swimsuit",
  "subcategory_accessories_tula": "Tote",
  "subcategory_accessories_rinonera": "Fanny Pack",
  "subcategory_accessories_lonchera": "Lunch Bag",
  "subcategory_accessories_billetera": "Wallet",
  "subcategory_accessories_monedero": "Coin Purse",
  "subcategory_accessories_tarjetero": "Card Holder",
  "subcategory_accessories_gorra": "Cap",
  "subcategory_accessories_cinturon": "Belt",
  "subcategory_clothing_pantalon": "Pants",
  "subcategory_clothing_jeans": "Jeans",
  "subcategory_clothing_vestido": "Dress",
  "subcategory_clothing_blazer": "Blazer",
  "subcategory_clothing_deportivo": "Sportswear",
  "subcategory_clothing_camiseta": "T-Shirt",
  "subcategory_clothing_pantaloneta": "Shorts",
  "subcategory_clothing_jogger": "Jogger",
  "subcategory_clothing_ropa_verano": "Summer clothes",
  "footer_company_text": "At Chic 44, we live fashion with passion and authenticity. We are inspired to offer collections that combine style, quality, and personality, designed for those who enjoy expressing who they are through what they wear.",
  "footer_store_copacabana": "Copacabana",
  "footer_store_copacabana_address": "Calle 50 #48-38",
  "footer_store_girardota": "Girardota",
  "footer_store_girardota_address": "Cra 18 #6-61",
  "footer_store_barbosa": "Barbosa",
  "footer_store_barbosa_address_1": "Cra 18 #11-28",
  "footer_store_barbosa_address_2": "Pasaje Comercial Unión Parque Local 108",
  "footer_contact_email": "chic44boutique@gmail.com",
  "search_suggested_categories": "Suggested Categories",
  "search_suggested_products": "Suggested Products",
  "search_no_results": "No results found for '{query}'"
};

const messages: Record<Language, Record<string, string>> = {
  es: esMessages,
  en: enMessages
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('es');

  const t = useCallback((key: string): string => {
    return messages[language][key] || key;
  }, [language]);
  
  const formatPrice = useCallback((price: number) => {
    return new Intl.NumberFormat(language === 'es' ? 'es-CO' : 'en-US', {
      style: 'currency',
      currency: 'COP',
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(price);
  }, [language]);

  const value = useMemo(() => ({ language, setLanguage, t, formatPrice }), [language, t, formatPrice]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};
